//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSchedule
    {
        public int ScheduleID { get; set; }
        public long EmployeeID { get; set; }
        public int ShiftTimeID { get; set; }
        public int WorkDayID { get; set; }
        public System.DateTime ShiftDate { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ShiftTimes ShiftTimes { get; set; }
        public virtual WorkDays WorkDays { get; set; }
    }
}
