//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salaries
    {
        public int SalaryID { get; set; }
        public long EmployeeID { get; set; }
        public decimal SalaryAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
